#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

if [ "$USE_VARS_STORE" == true ]; then
  trap "commit_vars_store ${PWD}" EXIT
fi

function main() {
  check_input_params

  if [ "${BBL_IAAS}" == "gcp" ]; then
    pushd "bbl-state"
      write_gcp_service_account_key
    popd
  fi

  setup_bosh_env_vars
  if [ "$REGENERATE_VARS_STORE" == true ]; then
    remove_vars_store
  fi

  bosh_interpolate
  bosh_deploy
}

main
